### ISSUE TITLE
SuspF.Spring: Unknown kind 'Hookean', version 0

### ISSUE THREAD

**Issue by ajay1606** [IPG-Automotive-UK/Aslan-CarMaker#2] opened 2022-03-10 06:15 UTC
Hello,

Thanks for sharing a very useful repository.
I am trying to run a carmaker simulator and i have followed the instruction provided, but getting error like 

```
		CarMaker ROS Node is disabled!
ERROR		SuspF.Spring: Unknown kind 'Hookean', version 0
```
Build Sucessful:
![image](https://user-images.githubusercontent.com/29722843/157599609-8fb458f6-880a-4de6-9a77-a126cfaa79fc.png)

Error Log:
![image](https://user-images.githubusercontent.com/29722843/157599518-685dde17-7765-463e-8906-c9e7de3c2904.png)

Any help is much appreciated. 

CarMaker version 10.2.1
Ubuntu:18.04
ROS: Melodic

Carmaker installation confined by running sample examples and also example ROS project working fine. 

Regards,
Ajay

**Comment by dmbarry86** [comment] 2022-03-10 06:51
@ajay1606 are you able to share the vehicle info file you are using?

**Comment by ajay1606** [comment] 2022-03-10 06:55
@dmbarry Thanks much for your quick response.

Here is the vehicle information file that currently using 
https://github.com/IPG-Automotive-UK/Aslan-CarMaker/blob/melodic/Data/Vehicle/Demo_IPG_CompanyCar
There are no modification made to above file.

After running command,` ./CMStart.sh `

![image](https://user-images.githubusercontent.com/29722843/157610603-9fcbf6ab-6914-436b-8ffe-3e363ae7e39f.png)

There is a popup screen that will open with the warning message Update project directory!

Before updating :
![image](https://user-images.githubusercontent.com/29722843/157610964-127cd6c2-6d56-4e3b-bb31-4ecbde7e0319.png)

After Updating:
![image](https://user-images.githubusercontent.com/29722843/157611124-6d5cf613-eab5-41fa-9fa4-b264f67c54f5.png)

![image](https://user-images.githubusercontent.com/29722843/157611209-65e6d72e-ce03-4727-8dfd-525a7e88e3d4.png)

After launching command (CarMaker GUI/ Extras/CMRosIF/Launch & Start Application)
![image](https://user-images.githubusercontent.com/29722843/157611399-86f121bb-5163-4af6-a691-45cdd1a9a443.png)

Am i missing anything? Any suggestions please?
Regards,
Ajay

**Comment by dmbarry86** [comment] 2022-03-10 11:09
@ajay1606 I think the problem might be the vehicle info file you are using which was built for CM9. You can try opening the infofile in CM10 and then saving it which should make the required key changes.

![infofile](https://user-images.githubusercontent.com/8976377/157650022-537c2f47-0a9f-4f93-b6fc-a483206fea57.gif)

If you compare this to the original file you should see the new suspension key has been added. To confirm the infofile is correct I would then recommend running a test run from the GUI with the default carmaker exe (not the custom Aslan exe). Once this is confirmed you can then switch to your custom Aslan exe and hopefully everything is ok.

**Comment by dmbarry86** [comment] 2022-03-10 11:22
> Here is the vehicle information file that currently using
> https://github.com/IPG-Automotive-UK/Aslan-CarMaker/blob/melodic/Data/Vehicle/Demo_IPG_CompanyCar
> There are no modification made to above file.

@ajay1606 I should also point out that this branch is for CarMaker 9 as detailed in the readme on that branch. It sounds like you are using CarMaker 10 and thus you should just use the main branch, which has an example infofile intended for CarMaker 10.

**Comment by ajay1606** [comment] 2022-03-10 13:57
@dmbarry86 , Thank you so much for Kind and detailed response. Indeed it helped me lot to understand this project more.
But still am unable to fix the issue. I have tried 2 options as you suggested.

1. Open and Saving configuration file to update according to Carmaker10.2.1
After open saving configuration file, i see few changes to file. But after running command (Launch & Start Application) error message again appears.

And the same configuration file working well with default Carmaker exe with Test run without any issues. 

```
		CarMaker ROS Node is disabled!
ERROR		SuspF.Spring: Unknown kind 'Hookean', version 0
```

2. Building Main branch fails with following error. So i have tried to build with melodic branch.
![image](https://user-images.githubusercontent.com/29722843/157676534-9ab527fc-f5ec-4bc0-90f5-12a752db9c42.png)

Could you please suggset me fix this error, so that i can continue on this.

Regards,
Ajay

**Comment by bogotm** [comment] 2022-03-10 14:19
Hello Ajay,

Which ROS version are you using? Also, I assume that /opt/ros/ros1 is a symbolic link that points to the desired ROS version directory as well. 

sensor_msgs/Image.h is one of the header files for the standard Sensor Messages package in ROS1. If I remember correctly, some of these header files changed at a certain point of the ROS1 development, so I need to look inside the correct ROS1 version to see why it's not there.

http://wiki.ros.org/sensor_msgs

**Comment by ajay1606** [comment] 2022-03-11 01:49
@dmbarry86 & @bogotm Thanks so much for your inputs, now able to build the main branch without any issues.
Also able to run TestRun project with Demo_IPG_Company_Car vehicle configuration.

@bogotm You are right, I missed the path to the symbolic link that points to ROS dir was an issue.

This is the sample result:
![image](https://user-images.githubusercontent.com/29722843/157785153-54c6b85c-9b89-4b82-92d4-464c597800b0.png)

But it seems, there are no simulation data topics published, ` rostopic list ` doesn't shows any topics published from simulator !
Am I missing something here !!

**Comment by bogotm** [comment] 2022-03-11 11:36
Hello,
It looks like the setup.bash is not found in the background Terminal.

Did you end up creating a symbolic link between ros1 and melodic? I would highly recommend that:
cd /opt/ros
sudo ln -sfn melodic ros1

**Comment by ajay1606** [comment] 2022-03-11 12:45
@bogotm, I have created a symbolic link as you suggested. But still, simulation data is not published, also there are no error messages!

![image](https://user-images.githubusercontent.com/29722843/157868980-9d09234b-ca75-44e5-9c3c-a7fe2afabfde.png)

**Comment by bogotm** [comment] 2022-03-11 15:16
Hi Ajay,

It looks like Aslan itself hasn't properly started either. Can you let me know if the Aslan GUI has come up too?

Also, just to help diagnose this, could you let me know what's happening in the RQT Node Graph? Obviously I have a lot of topics and a few nodes on mine, but I'm curious to see what happens when you run this project.

This is most of what my Node Graph looks like when running this project:

![image](https://user-images.githubusercontent.com/66947141/157895134-677fbd61-b1e4-4507-b20d-2684b9684296.png)

**Comment by ajay1606** [comment] 2022-03-12 08:52
Hello @bogotm, Thanks for the kind inputs, really appreciate it.

And after a few workarounds, I realized that Initially, ASLAN GUI was not opened. But after changing python version 3.6 to 2.7 now it working. Right after `Launch & Start Application` from CarMake GUI, I can see ASLAN Gui. After that, i checked for `rostopic list`, And I can see the following topics; 

Car maker and ASLAN GUI:
![image](https://user-images.githubusercontent.com/29722843/158010728-2128e851-e36f-4e01-a478-0bf5bd0cea8d.png)

Topic list:
![image](https://user-images.githubusercontent.com/29722843/158010852-0ca01022-1a90-451b-812c-b961f4a92af9.png)

In the above topics, data published following topics, but that also only `0`. (Not another than 0)
```
/sd_control
/sd_current_GPS
/sd_current_twist
/sd_imu_raw
```
Example `rostopic echo /sd_imu_raw`
![image](https://user-images.githubusercontent.com/29722843/158010937-c4d5efb2-07ce-484c-b243-c9597e73db41.png)

RQT Graph.
![image](https://user-images.githubusercontent.com/29722843/158010737-1152a19c-cf85-44a0-b0a2-7cb310ca94a9.png)

After start of ASLAN:
![image](https://user-images.githubusercontent.com/29722843/158011896-1d7d4ce9-0781-4b75-9e3a-88807d62c668.png)


I really appreciate your assistance in understanding and fixing the following!
1. How could we publish simulation data in rostopic ? Like (Lidar, GPS, and IMU)
2. To publish simulation data in ROS, DO we need to run Aslan along with it? Currently, i am looking to run Carmaker and check simulation data publishing in rostopic !

Looking to listen from you! Thank you so much

Regards,
Ajay

**Comment by bogotm** [comment] 2022-03-14 15:17
Hello Ajay,

You don't need to run ASLAN alongside this project. 

I can see that the CarMaker node is not in the graph, so it has not been started. 

I would check if you have loaded the correct CarMaker executable in the "Application Configuration" window:
https://github.com/IPG-Automotive-UK/Aslan-CarMaker#start-project

**Comment by ajay1606** [comment] 2022-03-15 05:21
@bogotom Thank you so much for your kind inputs so far, you are right I have loaded the wrong CarMaker executable. 

![image](https://user-images.githubusercontent.com/29722843/158310312-be40c5a1-0f20-4d37-b8cf-97184521fba1.png)
1.` Command (Executable): bin/CarMaker.linux64`
After choosing right executable am able to get node graph in `rqt_graph` as follows:
![image](https://user-images.githubusercontent.com/29722843/158311070-cb4173d2-bf0b-4b2a-9e02-8b6f8257ee29.png)

But strangely, the Vehicle doesn't move after clicking 'start'. 
![image](https://user-images.githubusercontent.com/29722843/158311613-37b8edda-079c-4a9a-a6aa-22993110efa8.png)

2. `Command (Executable): /opt/ipg/carmaker/linux64-10.2.1/bin/CarMaker.linux64`
In case of the above executable vehicle moving.

Could you please help me to fix this !

Regards,
Ajay

**Comment by bogotm** [comment] 2022-03-15 08:22
Hello Ajay,
This project "works" without Aslan, but after all, it's a bridge to the Aslan autonomous driving stack. The vehicle will not move because it's expecting Aslan to send it vehicle controls, otherwise, the car receives no Gas, Brake, or Steering input.

**Comment by ajay1606** [comment] 2022-03-15 08:31
@bogotm, Well, I was trying to acquire data (bag) by running a vehicle in a sample scenario. Then using bag file, construct PCD map and try NDT algorithm test with ASLAN.  

Later I would like to try in real time, by connecting ASLAN with CarMaker simulation. 

Any suggestion? to test ASLAN algorithm ?

regards,
Ajay

**Comment by dmbarry86** [comment] 2022-03-15 08:34
@ajay1606 I am closing off this issue now as it has moved quite far away from the original topic. Feel free to continue the discussion but I will close the issue. Your further questions may be more appropriate in the discussion section rather than here in issues. https://github.com/IPG-Automotive-UK/Aslan-CarMaker/discussions/categories/q-a

**Closed as completed by dmbarry86** 2022-03-15 08:34 UTC
